platform :ios, '8.0'
use_frameworks!

target ‘speedxSwift’ do

#GitHub上最为开发者认可的JSON解析类
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
#代替GCD 简洁的后台执行代码封装库
pod 'AsyncSwift', '~> 1.7.2'
#数据库
pod 'Realm', '~> 0.98.8'
# 著名的AFNetworking网络基础库Swift语言版
pod 'Alamofire', '~> 3.3'
# HanekeSwift：轻量带缓存高性能图片加载组件
pod 'HanekeSwift', '~> 0.10.1'

end 
